spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/transportador
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
